# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigencia', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome do fornecedor')),
                ('cnpj', models.CharField(max_length=50, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=25, verbose_name='telefone do fornecedor')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email do fornecedor')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço do fornecedor')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('vigencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vigencia.Vigencia')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'verbose_name': 'Fornecedor',
            },
        ),
    ]
