# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certidao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome da certidão')),
                ('tipo', models.CharField(max_length=20, verbose_name='tipo da certidão')),
                ('inicio_validade', models.CharField(blank=True, max_length=10, verbose_name='Data de início da validade da certidão')),
                ('final_validade', models.CharField(blank=True, max_length=10, verbose_name='Data final da validade da certidão')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/arquivos', verbose_name='Arquivo')),
                ('codigo_unico', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Código único')),
                ('is_auditada', models.BooleanField(default=False, verbose_name='Certidão auditada')),
                ('certidao_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Certidões',
                'verbose_name': 'Certidão',
            },
        ),
    ]
