# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigencia', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da unidade executora')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('code', models.CharField(max_length=100, verbose_name='Código da unidade executora')),
                ('type_school', models.CharField(max_length=30, verbose_name='Tipo de escola')),
                ('classification_school', models.CharField(choices=[('municipal', 'municipal'), ('estadual', 'estadual')], default='municipal', max_length=10, verbose_name='Classificação da escola')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Cidade')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('director', models.ForeignKey(db_column='director', default='diretor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_school', to=settings.AUTH_USER_MODEL, verbose_name='Diretor da escola')),
                ('vigencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_school', to='vigencia.Vigencia', verbose_name='Vigência da escola')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
    ]
