# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=5, verbose_name='Código do banco')),
                ('bank', models.CharField(max_length=100, verbose_name='Nome do banco')),
                ('agencia', models.CharField(max_length=50, verbose_name='Agência')),
                ('digito_agencia', models.CharField(max_length=10, verbose_name='Dígito do número da agência')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número da conta')),
                ('digito_account_number', models.CharField(max_length=10, verbose_name='Dígito do número da conta')),
                ('code', models.CharField(max_length=50, verbose_name='Código da fonte pagadora')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da conta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('director', models.ForeignKey(db_column='director', default='diretor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_bank_account', to=settings.AUTH_USER_MODEL, verbose_name='Conta do diretor')),
                ('vigencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_bank', to='vigencia.Vigencia', verbose_name='Vigência da conta bancária')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
            },
        ),
    ]
