# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigencia', '0001_initial'),
        ('school', '0001_initial'),
        ('fornecedor', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comprovante_pag', models.CharField(max_length=100, verbose_name='Número do comprovante de pagamento')),
                ('data_comprovante_pag', models.CharField(max_length=10, verbose_name='Data do comprovante de pagamento')),
                ('tipo_despesa', models.CharField(choices=[('Material', 'Material'), ('Serviço', 'Serviço')], default='Material', max_length=20, verbose_name='Tipo de Despesa')),
                ('tipo_documento', models.CharField(choices=[('Nota Fiscal', 'Nota Fiscal'), ('Fatura', 'Fatura'), ('Recibo', 'Recibo')], default='Nota Fiscal', max_length=20, verbose_name='Tipo de Documento')),
                ('tipo_nota_fiscal', models.CharField(choices=[('Manual', 'Manual'), ('Eletrônica', 'Eletrônica')], default='Manual', max_length=20, verbose_name='Tipo de Nota Fiscal')),
                ('file_tipo_documento', models.FileField(blank=True, null=True, upload_to='uploads/certificados/nf_or_fat', verbose_name='Arquivo de documento')),
                ('file_recibo', models.FileField(blank=True, null=True, upload_to='uploads/certificados/recibos', verbose_name='Arquivo de recibo')),
                ('file_comprovante', models.FileField(blank=True, null=True, upload_to='uploads/certificados/comprovantes', verbose_name='Arquivo do cheque')),
                ('file_proposta1', models.FileField(blank=True, null=True, upload_to='uploads/certificados/propostas', verbose_name='Arquivo de proposta #1')),
                ('file_proposta2', models.FileField(blank=True, null=True, upload_to='uploads/certificados/propostas', verbose_name='Arquivo de proposta #2')),
                ('file_proposta3', models.FileField(blank=True, null=True, upload_to='uploads/certificados/propostas', verbose_name='Arquivo de proposta #3')),
                ('file_outros', models.FileField(blank=True, null=True, upload_to='uploads/certificados/outros', verbose_name='Arquivo de outros documentos')),
                ('is_auditada', models.BooleanField(default=False, verbose_name='Despesa auditada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_bancaria', to='bank.Bank_account', verbose_name='Conta bancária')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='fornecedor.Fornecedor', verbose_name='Fornecedores')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='school.School', verbose_name='Escola')),
                ('vigencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_despesa', to='vigencia.Vigencia', verbose_name='Vigência da despesa')),
            ],
            options={
                'verbose_name_plural': 'Despesas',
                'verbose_name': 'Despesa',
            },
        ),
        migrations.CreateModel(
            name='ProdutoFat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='produto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('unidades', models.IntegerField(verbose_name='Quantidade')),
                ('tipo_unidade', models.CharField(default='', max_length=20, verbose_name='Unidade')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_fat', to='despesas.Despesa', verbose_name='Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoNf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='produto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('unidades', models.IntegerField(verbose_name='Quantidade')),
                ('tipo_unidade', models.CharField(default='', max_length=20, verbose_name='Unidade')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_nfm', to='despesas.Despesa', verbose_name='Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoNfelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='produto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('unidades', models.IntegerField(verbose_name='Quantidade')),
                ('tipo_unidade', models.CharField(default='', max_length=20, verbose_name='Unidade')),
                ('cfop', models.CharField(default='', max_length=20, verbose_name='CFOP')),
                ('o_cst', models.CharField(default='', max_length=20, verbose_name='O/CST')),
                ('ncm_sh', models.CharField(default='', max_length=20, verbose_name='NCM_SH')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_nfe', to='despesas.Despesa', verbose_name='Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='produto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Valor em reais')),
                ('unidades', models.IntegerField(verbose_name='Quantidade')),
                ('tipo_unidade', models.CharField(default='', max_length=20, verbose_name='Unidade')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_rec', to='despesas.Despesa', verbose_name='Produtos')),
            ],
        ),
    ]
