# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='Mensagem')),
                ('file_msg', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo em mensagem')),
                ('visualizada', models.BooleanField(default=False, verbose_name='Mensagem visualizada')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Hora e data de envio')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'verbose_name': 'Mensagem',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_auditoria', models.CharField(choices=[('despesas', 'despesas'), ('receitas', 'receitas'), ('dimensionamentos', 'dimensionamentos')], default='dimensionamentos', max_length=15, verbose_name='Chat da auditoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Hora e data de criação da sala')),
            ],
            options={
                'verbose_name_plural': 'Salas',
                'verbose_name': 'Sala',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='from_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_message', to='chat.Room', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
    ]
