# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.CharField(max_length=10, verbose_name='Data de início de vigência')),
                ('final_date', models.CharField(max_length=10, verbose_name='Data de final de vigência')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_vigencia', to=settings.AUTH_USER_MODEL, verbose_name='Conta do diretor')),
            ],
            options={
                'verbose_name': 'Vigência',
                'verbose_name_plural': 'Vigências',
            },
        ),
    ]
